---
# Template configuration files for locatedb

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ locatedb_templates_copy }}"
  when: locatedb_copy_templates
